version: "3"
services:
  web:
    image: nginx
    links:
     - graphql-api
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
  graphql-api:
    image: rlkamradt/graphql-api:latest
    ports:
     - "3000:3000"
