version: "3"
services:
  web:
    image: nginx
    links:
     - lilys-api
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.secret:/etc/certs
    ports:
     - "443:443"
  lilys-api:
    image: iammuse87/lilys-api:latest
    ports:
     - "3000:3000"
